### ISSUE TITLE
Selection sort in C, C++ and Python

### ISSUE THREAD

**Issue by shubanms** [justforfunweb/algorithms#1]
# Feature description
The selection sort algorithm sorts an array by repeatedly finding the minimum element (considering ascending order) from the unsorted part and putting it at the beginning. 

The algorithm maintains two subarrays in a given array.

- The subarray which already sorted. 
- The remaining subarray was unsorted.

In every iteration of the selection sort, the minimum element (considering ascending order) from the unsorted subarray is picked and moved to the beginning of unsorted subarray. 

After every iteration sorted subarray size increase by one and unsorted subarray size decrease by one.

Implementation of Selection sort in three languages.

# Authors
[@Shuban M S](https://github.com/shubanms)

# Requirements

Knowledge in C, C++ and Python

## Links / references
[Selection sort](https://www.geeksforgeeks.org/selection-sort/)

**Comment by justforfunweb** [comment]
@shubanms completed issue with pull request #2
