### ISSUE TITLE
Bubble sort in C, C++ and Python

### ISSUE THREAD

**Issue by shubanms** [justforfunweb/algorithms#3]
# Feature description
Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in the wrong order. This algorithm is not suitable for large data sets as its average and worst-case time complexity is quite high.

Implementation of Bubble sort in three languages.

# Authors
[@Shuban M S](https://github.com/shubanms)

# Requirements

Knowledge in C, C++ and Python

## Links / references
[Bubble Sort](https://www.geeksforgeeks.org/bubble-sort/)

**Comment by justforfunweb** [comment]
@shubanms completed issue with pull request #4
