### ISSUE TITLE
Insertion sort in C, C++ and Python

### ISSUE THREAD

**Issue by shubanms** [justforfunweb/algorithms#6]
# Feature description
Insertion sort is a simple sorting algorithm that works similar to the way you sort playing cards in your hands. The array is virtually split into a sorted and an unsorted part. Values from the unsorted part are picked and placed at the correct position in the sorted part.

Implementation of Bubble sort in three languages.

# Authors
[@Shuban M S](https://github.com/shubanms)

# Requirements

Knowledge in C, C++ and Python

## Links / references
[Insertion Sort](https://www.geeksforgeeks.org/insertion-sort/)

**Comment by justforfunweb** [comment]
@shubanms completed issue with pull request #7
